# Generated by Django 4.2.3 on 2024-03-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correcr',
            new_name='is_correct',
        ),
    ]
